### PR TITLE
Fix Backbone.Model.prototype.collection

### PR DESCRIPTION
**Pull request by skotchio**

### CODE REVIEW

**Comment by skotchio** [comment]
Hi. What's problem with this PR? Does it wrong?

**Comment by lukeasrodgers** [comment]
I believe that `type` here should be `Object` not `Function`, though my whole approach of using prototype properties to stand in for instance variables isn't ideal.

**Comment by lukeasrodgers** [comment]
The overall idea was good though, feel free to re-open a PR with that fix, and I'll merge it.

**Comment by skotchio** [comment]
Done https://github.com/lukeasrodgers/backbone-js-externs/pull/3

**Pull request closed without merging**
